coverage:
  status:
    project:
      default: # This can be anything, but it needs to exist as the name
        # basic settings
        target: auto
        threshold: 5%
        base: auto
        # advanced settings
        branches:
          - master
        if_ci_failed: error #success, failure, error, ignore
        only_pulls: false
        flags:
          - frontend
        paths:
          - src/frontend
        removed_code_behavior: off #removals_only, fully_covered_patch, adjust_base",